name: mi_card_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
     - images/kaush1.jpg
     - images/kaush.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

    - family: AkayaTelivigala
      fonts:
        - asset: fonts/AkayaTelivigala-Regular.ttf


    - family: ABeeZee
      fonts:
        - asset: fonts/ABeeZee-Regular.ttf
        - asset: fonts/ABeeZee-Italic.ttf
          style: italic